#!/bin/bash

echo Start


echo = STEP 1 - Cloning  demo-integration/demo-integration-backend 
git clone git@gitlab.com:demo-integration/demo-integration-backend.git --quiet
cd ./demo-integration-backend
rm -f ./src/main/resources/application.properties

echo == STEP 2 - Generate package
mvn versions:set -DnewVersion=$1 --quiet
mvn clean install > maven.log
mkdir ./target/tmp

echo === STEP 3 - Build image
podman build -t iamrogerio2/demo-integration-backend:$1 . > ./target/tmp/podman-build.log

echo ==== STEP 4 - Push Image to Registry
podman  push iamrogerio2/demo-integration-backend:$1 -q 

echo ===== STEP 5 - Clone GitOps Repository
cd ./target/tmp
git clone git@gitlab.com:demo-integration/demo-integration-gitops.git --quiet

echo ====== STEP 6 - Cleaning
cd ../../..
pwd
rm -rfv ./demo-integration-backend 

echo End