namespace: demo-integration
database: 
  mysql: 
   image: docker.io/library/mysql:8.0   
backend: 
   app: 
     name: 'demo-integration-backend'   
   image: docker.io/iamrogerio2/demo-integration-backend:1.0.0  
frontend: {}
