kind: ConfigMap
apiVersion: v1
metadata:
  name: '{{ .Values.backend.app.name }}'
  namespace: '{{ .Values.namespace }}'
data:
  application.properties: |-

    camel.springboot.name=demo-integration-backend

    camel.component.servlet.mapping.contextPath=/*

    server.address=0.0.0.0

    server.port=8080

    management.server.port=8081
    
    demo.integration.smtp.host=teste@teste.com

    demo.integration.smtp.username=username
    
    demo.integration.smtp.password=password

