kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.backend.app.name }}
  namespace: '{{ .Values.namespace }}'
  labels:
    app: {{ .Values.backend.app.name }}
    app.kubernetes.io/component: {{ .Values.backend.app.name }}
    app.kubernetes.io/instance: {{ .Values.backend.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: {{ .Values.backend.app.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: {{ .Values.backend.app.name }}
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: {{ .Values.backend.app.name }}
          image: '{{ .Values.backend.image}}'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - containerPort: 9779
              protocol: TCP
          env:
            - name: DATABASE_MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo-integration-backend
                  key: DATABASE_MYSQL_USERNAME
            - name: DATABASE_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-integration-backend
                  key: DATABASE_MYSQL_PASSWORD
            - name: DATABASE_MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: demo-integration-backend
                  key: DATABASE_MYSQL_URL
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600