kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.backend.app.name }}'
  namespace: {{ .Values.namesapace }}
  labels:
    app: demo-integration-backend
    app.kubernetes.io/component: '{{ .Values.backend.app.name }}'
    app.kubernetes.io/instance: '{{ .Values.backend.app.name }}'
    app.kubernetes.io/name: '{{ .Values.backend.app.name }}'
    app.kubernetes.io/part-of: '{{ .Values.backend.app.name }}'
    app.openshift.io/runtime-version: '1.0'
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole 
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
    - name: 9779-tcp
      protocol: TCP
      port: 9779
      targetPort: 9779
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: '{{ .Values.backend.app.name }}'
    deploymentconfig: '{{ .Values.backend.app.name }}'
status:
  loadBalancer: {}
