kind: Secret
apiVersion: v1
metadata:
  name: mysql
  namespace: '{{ .Values.namespace }}'
  labels:
    template: mysql-persistent-template
    template.openshift.io/template-instance-owner: 32d36309-3a52-48f0-9a0f-42cbd0fd245c
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: ZGVtb2ludGVncmF0aW9uZGI=
  database-password: YWRtaW4=
  database-root-password: cm9vdA==
  database-user: YWRtaW4=
type: Opaque
